version: '3.5'

services:

  cb:
    build: couchbase-docker/.
    container_name: cb

    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"

    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Admin
      - COUCHBASE_ADMINISTRATOR_PASSWORD=halco1002
      - COUCHBASE_BUCKET=videoteka
      - PORT=8091

#    volumes:
#      - cb_data:/opt/couchbase/var

  videoteka:
    build: .
    container_name: videoteka-mvn
    ports:
      - "8200:8200"

    restart: always

    depends_on:
      - cb

    environment:
      - server.port=8200
      - spring.couchbase.connection-string=couchbase://cb
      - spring.couchbase.username=Admin
      - spring.couchbase.password=halco1002
      - spring.data.couchbase.bucket-name=videoteka
      - FUSIONAUTH_URL=localhost:8085


networks:
  default:
    external:
      name: videoteka_network

#networks:
#  default:
#    external:
#      name: mynetwork

#volumes:
#  cb_data:


