version: '3.5'

services:

  cb:
    build: couchbase-docker/.
    container_name: cb

    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"

    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=${COUCHBASE_USERNAME}
      - COUCHBASE_ADMINISTRATOR_PASSWORD=${COUCHBASE_PASSWORD}
      - COUCHBASE_BUCKET=${COUCHBASE_BUCKET}
      - PORT=${CB_PORT}

#    volumes:
#      - cb_data:/opt/couchbase/var

  videoteka:
    build: .
    container_name: videoteka-mvn
    ports:
      - "8200:8200"

    restart: always

    depends_on:
      - cb
      
#    networks:
#      - videoteka_network

    environment:
      - server.port=${VIDEOTEKA_PORT}
      - spring.couchbase.connection-string=couchbase://cb
      - spring.couchbase.username=${COUCHBASE_USERNAME}
      - spring.couchbase.password=${COUCHBASE_PASSWORD}
      - spring.data.couchbase.bucket-name=${COUCHBASE_BUCKET}
      - FUSIONAUTH_URL=fusionauth-microservice:8085
      - fusionauth.jwt.secret=${JWT_SECRET}
      - fusionauth.appId=${FUSIONAUTH_APP_ID}
      - apiKey=${EXTERNAL_API_KEY}


networks: 
  default: 
    external: 
      name: videoteka_network

#networks:
#  default:
#    external:
#      name: mynetwork

#volumes:
#  cb_data:


